### ISSUE TITLE
CVEs in H2 dependency

### ISSUE THREAD

**Issue by magick93** [yavin-dev/gsheet-jdbc#5]
Hi

Really cool project. Thanks for sharing.

FYI - there are some CVEs detected in the H2 dependencies - https://mvnrepository.com/artifact/dev.yavin/gsheet-jdbc/1.0.6

**Comment by aklish** [comment]
Thanks.  Will patch soon.

**Comment by aklish** [comment]
1.0.7 has latest H2.
